import { GeoElement } from './types';

export const COMMUNITIES: GeoElement[] = [
  { id: 'and', name: 'Andalucía', type: 'communities' },
  { id: 'ara', name: 'Aragón', type: 'communities' },
  { id: 'ast', name: 'Asturias', type: 'communities' },
  { id: 'bal', name: 'Islas Baleares', type: 'communities' },
  { id: 'can', name: 'Canarias', type: 'communities' },
  { id: 'cnt', name: 'Cantabria', type: 'communities' },
  { id: 'clm', name: 'Castilla-La Mancha', type: 'communities' },
  { id: 'cyl', name: 'Castilla y León', type: 'communities' },
  { id: 'cat', name: 'Cataluña', type: 'communities' },
  { id: 'ext', name: 'Extremadura', type: 'communities' },
  { id: 'gal', name: 'Galicia', type: 'communities' },
  { id: 'mad', name: 'Madrid', type: 'communities' },
  { id: 'mur', name: 'Murcia', type: 'communities' },
  { id: 'nav', name: 'Navarra', type: 'communities' },
  { id: 'pva', name: 'País Vasco', type: 'communities' },
  { id: 'rio', name: 'La Rioja', type: 'communities' },
  { id: 'val', name: 'Comunidad Valenciana', type: 'communities' },
  { id: 'ceu', name: 'Ceuta', type: 'communities' },
  { id: 'mel', name: 'Melilla', type: 'communities' },
];

export const PROVINCES: GeoElement[] = [
  { id: 'Albacete', name: 'Albacete', type: 'provinces' },
  { id: 'Alicante', name: 'Alicante', type: 'provinces' },
  { id: 'Almería', name: 'Almería', type: 'provinces' },
  { id: 'Araba', name: 'Álava', type: 'provinces' },
  { id: 'Asturias', name: 'Asturias', type: 'provinces' },
  { id: 'Ávila', name: 'Ávila', type: 'provinces' },
  { id: 'Badajoz', name: 'Badajoz', type: 'provinces' },
  { id: 'Balears', name: 'Baleares', type: 'provinces' },
  { id: 'Barcelona', name: 'Barcelona', type: 'provinces' },
  { id: 'Bizkaia', name: 'Vizcaya', type: 'provinces' },
  { id: 'Burgos', name: 'Burgos', type: 'provinces' },
  { id: 'Cáceres', name: 'Cáceres', type: 'provinces' },
  { id: 'Cádiz', name: 'Cádiz', type: 'provinces' },
  { id: 'Cantabria', name: 'Cantabria', type: 'provinces' },
  { id: 'Castelló', name: 'Castellón', type: 'provinces' },
  { id: 'Ciudad Real', name: 'Ciudad Real', type: 'provinces' },
  { id: 'Córdoba', name: 'Córdoba', type: 'provinces' },
  { id: 'Coruña', name: 'La Coruña', type: 'provinces' },
  { id: 'Cuenca', name: 'Cuenca', type: 'provinces' },
  { id: 'Gipuzkoa', name: 'Guipúzcoa', type: 'provinces' },
  { id: 'Girona', name: 'Gerona', type: 'provinces' },
  { id: 'Granada', name: 'Granada', type: 'provinces' },
  { id: 'Guadalajara', name: 'Guadalajara', type: 'provinces' },
  { id: 'Huelva', name: 'Huelva', type: 'provinces' },
  { id: 'Huesca', name: 'Huesca', type: 'provinces' },
  { id: 'Jaén', name: 'Jaén', type: 'provinces' },
  { id: 'León', name: 'León', type: 'provinces' },
  { id: 'Lleida', name: 'Lérida', type: 'provinces' },
  { id: 'Lugo', name: 'Lugo', type: 'provinces' },
  { id: 'Madrid', name: 'Madrid', type: 'provinces' },
  { id: 'Málaga', name: 'Málaga', type: 'provinces' },
  { id: 'Murcia', name: 'Murcia', type: 'provinces' },
  { id: 'Navarra', name: 'Navarra', type: 'provinces' },
  { id: 'Ourense', name: 'Orense', type: 'provinces' },
  { id: 'Palencia', name: 'Palencia', type: 'provinces' },
  { id: 'Palmas', name: 'Las Palmas', type: 'provinces' },
  { id: 'Pontevedra', name: 'Pontevedra', type: 'provinces' },
  { id: 'Rioja', name: 'La Rioja', type: 'provinces' },
  { id: 'Salamanca', name: 'Salamanca', type: 'provinces' },
  { id: 'Santa Cruz de Tenerife', name: 'Santa Cruz de Tenerife', type: 'provinces' },
  { id: 'Segovia', name: 'Segovia', type: 'provinces' },
  { id: 'Sevilla', name: 'Sevilla', type: 'provinces' },
  { id: 'Soria', name: 'Soria', type: 'provinces' },
  { id: 'Tarragona', name: 'Tarragona', type: 'provinces' },
  { id: 'Teruel', name: 'Teruel', type: 'provinces' },
  { id: 'Toledo', name: 'Toledo', type: 'provinces' },
  { id: 'València', name: 'Valencia', type: 'provinces' },
  { id: 'Valladolid', name: 'Valladolid', type: 'provinces' },
  { id: 'Zamora', name: 'Zamora', type: 'provinces' },
  { id: 'Zaragoza', name: 'Zaragoza', type: 'provinces' },
];
